{
 "title": "Taxi_Duration_Monitoring",
 "time": { "from": "2182-11-14T20:20:15.011Z", "to": "2191-05-16T11:47:23.011Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Run Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT\n    CASE r.status\n        WHEN 'FINISHED' THEN 'Success'\n        ELSE 'Failed'\n    END AS run_status,\n    COUNT(r.run_uuid) AS run_count\nFROM\n    runs r\nWHERE\n    r.experiment_id = 1\n    AND r.status IN ('FINISHED', 'FAILED')\nGROUP BY\n    run_status;\n",
     "rawQueryText": "SELECT\n    CASE r.status\n        WHEN 'FINISHED' THEN 'Success'\n        ELSE 'Failed'\n    END AS run_status,\n    COUNT(r.run_uuid) AS run_count\nFROM\n    runs r\nWHERE\n    r.experiment_id = 1\n    AND r.status IN ('FINISHED', 'FAILED')\nGROUP BY\n    run_status;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Metrics Summary",
   "type": "stat",
   "description": "This bar chart displays individual performance metrics—RMSE, MAE, and R2—highlighting key evaluation criteria for quick assessment of model accuracy and fit.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n    r.name AS model_name,\n    AVG(CASE WHEN m.key = 'RMSE' THEN m.value END) AS RMSE,\n    AVG(CASE WHEN m.key = 'mae' THEN m.value END) AS mae,\n    AVG(CASE WHEN m.key = 'R2' THEN m.value END) AS R2\nFROM\n    metrics m\nJOIN\n    runs r ON m.run_uuid = r.run_uuid\nWHERE\n    m.key IN ('RMSE', 'mae', 'R2')\n    AND r.experiment_id = 1\nGROUP BY\n    r.name, r.run_uuid;",
     "rawQueryText": "SELECT\n    r.name AS model_name,\n    AVG(CASE WHEN m.key = 'RMSE' THEN m.value END) AS RMSE,\n    AVG(CASE WHEN m.key = 'mae' THEN m.value END) AS mae,\n    AVG(CASE WHEN m.key = 'R2' THEN m.value END) AS R2\nFROM\n    metrics m\nJOIN\n    runs r ON m.run_uuid = r.run_uuid\nWHERE\n    m.key IN ('RMSE', 'mae', 'R2')\n    AND r.experiment_id = 1\nGROUP BY\n    r.name, r.run_uuid;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Model Performance",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT\n    r.start_time * 1000 AS \"time\",  -- Ensure time is in milliseconds\n    m.key AS metric_type,\n    AVG(m.value) AS metric_value,\n    r.name AS model_name \nFROM\n    runs r\nJOIN\n    metrics m ON r.run_uuid = m.run_uuid\nWHERE\n    r.experiment_id = 1  \n    AND m.key IN ('RMSE', 'mae', 'R2') \n    AND r.status = 'FINISHED'  \nGROUP BY\n    r.start_time, m.key, r.name  \nORDER BY\n    r.start_time;\n",
     "rawQueryText": "SELECT\n    r.start_time * 1000 AS \"time\",  -- Ensure time is in milliseconds\n    m.key AS metric_type,\n    AVG(m.value) AS metric_value,\n    r.name AS model_name \nFROM\n    runs r\nJOIN\n    metrics m ON r.run_uuid = m.run_uuid\nWHERE\n    r.experiment_id = 1  \n    AND m.key IN ('RMSE', 'mae', 'R2') \n    AND r.status = 'FINISHED'  \nGROUP BY\n    r.start_time, m.key, r.name  \nORDER BY\n    r.start_time;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Registered Models",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT \n    rm.name AS Model_Name,\n    mv.version AS Version,\n    datetime(mv.creation_time / 1000, 'unixepoch') AS Creation_Time,\n    datetime(mv.last_updated_time / 1000, 'unixepoch') AS Last_Updated_Time\nFROM registered_models rm\nLEFT JOIN model_versions mv ON rm.name = mv.name\nORDER BY rm.name, mv.version DESC;\n",
     "rawQueryText": "SELECT \n    rm.name AS Model_Name,\n    mv.version AS Version,\n    datetime(mv.creation_time / 1000, 'unixepoch') AS Creation_Time,\n    datetime(mv.last_updated_time / 1000, 'unixepoch') AS Last_Updated_Time\nFROM registered_models rm\nLEFT JOIN model_versions mv ON rm.name = mv.name\nORDER BY rm.name, mv.version DESC;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}